### ISSUE TITLE
Add "reset to defaults" button to the user settings

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#10]
From Taranis-NG created by [not4Pedro](https://github.com/not4Pedro): ait-cs-IaaS/Taranis-NG#161  

Add a reset button of the settings to factory (default) settings in the user settings.

**Comment by ewoiset** [comment]
see: 

src/views/users/settings/UserSettings.vue
src/stores/SettingsStore.js


compare: reset_user in MainStore

**Comment by not4Pedro** [comment]
I suggest resetting the values on click, but not saving it immediately to the database. This would be a useful mechanism in case of misclicks.
