### ISSUE TITLE
CardAssess edit Tags

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#100]
Add a feature to the "CardAssess" component, that allows users to manipulate the tags. (Edit, remove, add)

* add endpoint to api/assess.py to allow editing Tags see => https://github.com/taranis-ai/taranis-ai/blob/a604f6efaf4ff412c8b7584418369da91e23e3bf/src/core/core/api/worker.py#L180 for reference
* Update /enter endpoint to allow for non manually created items, setting all fields except tags to `disabled`

**Comment by ewoiset** [comment]
see  issue #102
