### ISSUE TITLE
Mail-Publisher

### ISSUE THREAD

**Issue by ewoiset** [taranis-ai/taranis-ai#103]
Erstellte Reports über ein Product automatisiert über eine Email-Vorlage (Adressat, Betreff, plain-text oder pdf als attachment, Formatierung) versenden
___________________________

Send created reports about a product  - automatically via an email template (recipient, subject, plaintext or pdf as attachment, formatting).

Reqs:
- No encryption for now (PGP, etc.)
- Send an email to a preconfigured email address
- Add auto email option to settings to preconfigure the email address, and/or to enable/disable automatic email sending.
- It would most probably appear on the publisher level (email address and possible signing using PGP)

Qs:   
- How to trigger the sending - once in a time like every 30 minutes it would check new products, so the new products are not sent with errors.

Consider: https://github.com/CZ-NIC/envelope/issues/29#issue-1780690838

**Comment by b3n4kh** [comment]
USER configuration:
* SERVER_ADDRESS  : str
* SERVER_PORT         : int
* SERVER_TLS            : bool => https://docs.python.org/3/library/smtplib.html#smtplib.SMTP_SSL
* USERNAME             : str | None
* PASSWORD             : str | None
*

**Comment by not4Pedro** [comment]
note that you will need to change your Gmail (or other clients) settings to be able to send email via SMTP from it

**Comment by not4Pedro** [comment]
> PASSWORD : str | None
will we do it with **** field or clear text @b3n4kh
