### ISSUE TITLE
Digest Splitting 

### ISSUE THREAD

**Issue by ewoiset** [taranis-ai/taranis-ai#104]
The option of splitting the information from a source with multiple contents (e.g. [daily report](http://cert.at/cert-at.de.all.rss_2.0.xml), weekly report) into individually created items in order to enrich different stories.

[Example News Item
](https://dev.taranis.ai/story/9164)Every "row" in a should be it's own NewsItem

- [x] Add option to OSINT Source to allow enabling "digest splitting mode" by adding a parameter of type "CheckBox" to [pre_seed_data](https://github.com/taranis-ai/taranis-ai/blob/master/src/core/core/managers/pre_seed_data.py#L5)
- [x] Add functionality to [RSS Collector](https://github.com/taranis-ai/taranis-ai/blob/master/src/worker/worker/collectors/rss_collector.py#L103) to split collected items into multiple before submitting them to Core

**Comment by not4Pedro** [comment]
sources with summary
https://us-cert.cisa.gov/ncas/bulletins.xml

**Comment by not4Pedro** [comment]
Split every link to a separate item. No other logic is needed.
