### ISSUE TITLE
Assess: adapt news items

### ISSUE THREAD

**Issue by ewoiset** [taranis-ai/taranis-ai#108]
- [ ]  also add timestamp to Date in news item
     - current behavior: news item aggregate only displays date and no time stamp
     - wanted behavior: news item aggregate should display time as well as date (as in the single items) 
     -  make sure it also workes in detail view and for clusters
     - CERT request: "Published" ist nur mit Datum sichtbar in der Assess-Ansicht, braucht auch Uhrzeit in der Assess-Ansicht

- [ ] add source + its icon to news item aggregate if only one item is in aggregate
    - CERT request:  Icon der Quelle + Quelleninfos auf oberster Ebene wenn nur 1 NewsItem in Story

 
 - [ ]  Tags are displayed in next line in some asses news items (see screenshot underneath)

**Comment by ewoiset** [comment]
![Image](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/861c93ee-bd8e-47b5-b508-6be4eea5cbbc)

**Comment by b3n4kh** [comment]
For the "StoryMetaInfo" always display the article of the first newsitem. If it is only one, it is just "the article" if there are multiple, the first article should be the most descriptive (even if it isn't yet it should be after future story clustering improvements)
