### ISSUE TITLE
database is unhealthy

### ISSUE THREAD

**Issue by meetgyn** [taranis-ai/taranis-ai#125]
I'm not able to climb the docker. Return this error message
​
![image](https://github.com/taranis-ai/taranis-ai/assets/3695608/c38a4b18-2dfe-4816-9b66-db2e5a9022e7)

**Comment by b3n4kh** [comment]
It might be that you haven't set a `POSTGRES_PASSWORD`.

Copying env.sample to a file called .env will give you same defaults for a testsetup:

`cp env.sample .env`
