### ISSUE TITLE
updating user settings: new entry in user_profile table is made 

### ISSUE THREAD

**Issue by ewoiset** [taranis-ai/taranis-ai#132]
When updating user profile settings (/user/settings) a new entry is made in the user_profile db, when reseting settings two entries are made 

wished behavior: user's entry should be updated

additionally is ondelete='cascade' really wished for user.profile_id and hotkey.user_profile_id --> everytime a user_profile entry is deleted the user is deleted? 

![Screenshot from 2024-02-02 18-43-00](https://github.com/taranis-ai/taranis-ai/assets/88492381/fe8bc819-6fc6-491b-afb2-87fc8333a2eb)

**Comment by b3n4kh** [comment]
Sounds like the ondelete is the wrong way around. 

Everytime a user is deleted his profile is deleted. 

Would be the correct one

**Comment by b3n4kh** [comment]
Should be fixed there needs to be at least one or two unit test for this issue to be actually solved
