### ISSUE TITLE
Allow viewing and editing WorkerType Parameters

### ISSUE THREAD

**Issue by not4Pedro** [taranis-ai/taranis-ai#171]
Currently, there are no required fields of the particular publishers, even though, it would make sense to have some of the fields as required.

This requires to enhance [class Parameters](https://github.com/taranis-ai/taranis-ai/blob/a5c257186f10ac91bd0035f9c3fd8dedc658a147/src/core/core/api/config.py#L181-L184) in `api/config.py` to allow updating the presets of the various workers.

Right now they are only set once while [pre-seeding](https://github.com/taranis-ai/taranis-ai/blob/08fa2d933e40bdabad5c1c53729af6fccf11ecee/src/core/core/managers/pre_seed_data.py#L1)

This issue needs a new [Permission](https://github.com/taranis-ai/taranis-ai/blob/master/src/core/core/model/permission.py) for the newly added endpoints.

`CONFIG_PARAMETER_*`

The user should only be able to update existing `parameter`, values and rules, and name and description of the worker.
He should not be able to remove or add any new parameters, nor change parameter type or worker type.

Update the test https://github.com/taranis-ai/taranis-ai/blob/a0d8123007da6edd30adf17cbb377a85fea943ef/src/core/tests/functional/config/test_config.py#L431

**Comment by b3n4kh** [comment]
If this functionality exists in a next step it could be used to allow editing these parameters directly on:

https://dev.taranis.ai/config/workertypes => WorkerTypesView.vue
