### ISSUE TITLE
Refactor attribute behavior in report item types

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#18]
From Taranis-NG created by [ewoiset](https://github.com/ewoiset): ait-cs-IaaS/Taranis-NG#150  

Current behavior: 
- When attributes are added to report types they are not automatically added to existing reports 
- When attributes are deleted from report types, reports automatically change. 

Is this the wanted behavior?

**Comment by b3n4kh** [comment]
One possible solution could be to just "lock" attributes that are referenced in a report item.

**Comment by not4Pedro** [comment]
When you create a new attribute group. Add a new attribute (Link), the last attribute group stays blank, no input fields appear in the New Report view.

**Comment by b3n4kh** [comment]
Fixed with: https://github.com/taranis-ai/taranis-ai/commit/172f97405834edadc0358c1ba488123b3fbe5aa4
