### ISSUE TITLE
High CPU usage / memory requirements

### ISSUE THREAD

**Issue by jfstenuit** [taranis-ai/taranis-ai#180]
I just imported my list of RSS feeds (~40 feeds) to a virgin instance of taranis-ai (good think you can export from taranis-ng and import back in taranis-ai).

I first tried with a VM with 16GB RAM. It doesn't seem to be sufficient. With the current set-up, the requirements are around 20.5 GB of RAM.

Then, after a few minutes, I'm beginning to have a high CPU usage. I'm currently testing with 6 vCores, but the situation is unchanged : after a few minutes, the system is maxing out all available CPU cores. Celery seem to spawn one "worker worker" process per core and each of those processes eat up 100% of the CPU.

If this is not expected, it may indicate a DoS condition with one of my feeds.

Unfortunately, troubleshooting instructions are scarce in the documentation.

**Comment by b3n4kh** [comment]
Thank you for the issue!

It is true, the default behavior for celery is one worker per CPU core, but I will expose [worker_concurrency](https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-worker_concurrency) setting via an environment variable to make this easier configurable.

# Memory Requirements
The necessary memory and resource requirements are hard to predict as they heavily depend on the Feeds. Usually there is a very huge spike for the initial "gather" which then ebbs down for the continues gathering. A lot of sources keep a very long history in their RSS Feed, but if you collect every two hours ( the default ) you won't see as many articles.

# Troubleshooting
The troubleshooting itself is unfortunately tricky in this distributed async environment. Under `/config/workers` you can see if any of the queues have unfinished tasks. Additionally, there is now a new feature in `/config/sources` under the actions column called `preview` it is in a very early development phase, but it allows you to review what this source would collect, before running the actual collection.

# Wrap Up
The resource hungriest here is usually the `NLP Tagging Bot` found under `/config/bots`.
There you can toggle `RUN_AFTER_COLLECTOR` to false, which will drastically reduce your resource requirements, but it will also reduce the number of available tags per story.
I will create a task on creating a compose file with some kind of log aggregation added, to make it easier to review worker logs. Maybe in the future we can even add some kind of simplified worker log viewer to Taranis Admin panel.


We are going to release our first `stable` version next week, it will be under [releases](https://github.com/taranis-ai/taranis-ai/releases). Hope the explanation helps, if there are any other questions feel free to ask, or please close the issue if this was helpful for now.

**Comment by jfstenuit** [comment]
I think the task resulting from this issue is really in the area of documentation. Others may stumble on to this issue when testing Taranis-ai and feel discouraged. 
The current minimal requirements on README.md mention "To use all NLP features make sure to have at least: 16 GB RAM, 4 CPU cores and 50GB of disk storage.". In my experience, this is more like 24GB RAM and 8 CPU cores, when you have more than one handfull test feeds.
The fact that the NLP tagging bot will use a lot of CPU for a long time upon first ingestion of the feeds should also be mentionned, so that first-time users are not surprised.
