### ISSUE TITLE
Collect multi Weeks of data

### ISSUE THREAD

**Issue by ewoiset** [taranis-ai/taranis-ai#184]
- [ ] Create a new instance - like dev/stage 
- [ ] Gather news items for given sources (File can be found in private NextCloud) + run NLP + tagging bot etc BUT NO CLUSTERING! 
- [ ] Write script to save json of items of each day

current state:

- [x] almost 1 on 1 copy of dev instance
- [x] beat is in place
- [x] save at 00:00 last two days

**Comment by ewoiset** [comment]
[osint_currated_gold (1).json](https://github.com/taranis-ai/taranis-ai/files/14804345/osint_currated_gold.1.json)

**Comment by ewoiset** [comment]
VM:

Hostname: V3LS2415
IP: 10.103.251.112

**Comment by ewoiset** [comment]
[osint_sources_currated (1).json](https://github.com/taranis-ai/taranis-ai/files/15189249/osint_sources_currated.1.json)

**Comment by ewoiset** [comment]
[osint_currated_gold (2).json](https://github.com/taranis-ai/taranis-ai/files/15189260/osint_currated_gold.2.json)

**Comment by ewoiset** [comment]
do it exactly as on dev .. 

- use beat to collect 
- store data in json once a day - at 20:00ish / night 
- DONT use summary or story bots

**Comment by not4Pedro** [comment]
- use publish date
- last two days
- use worker endpiont

**Comment by not4Pedro** [comment]
complete, check the collected data in /opt/dev-taranis-collect/collected
