### ISSUE TITLE
Create 'Simple'_WEB_COLLECTOR

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#22]
Create a new collector that just uses trafilatura to parse the website and create a new item if there is a diff to last parsed.

- [ ] with the option of parsing specific text parts, e.g. with Xpath
- [ ] Add test to example page: https://www.wienernetze.at/stromversorgung

**Comment by b3n4kh** [comment]
Example page: https://www.wienernetze.at/stromversorgung

**Comment by ewoiset** [comment]
Meeting 2023-12-04: HTML only

**Comment by not4Pedro** [comment]
The collector has a [bug](https://github.com/taranis-ai/taranis-ai/pull/114#issue-2070977364) by default, when passing some websites. 

Moreover, the XPath needs sanitation. In some cases it contains double quotes and maybe some other indicovered formats, which break the code.
