### ISSUE TITLE
NewsItem not collected when website from RSS Feed returns error

### ISSUE THREAD

**Issue by StephanPillhofer** [taranis-ai/taranis-ai#225]
I am not sure if this is a bug or intentional, but no news item is created when the RSS Collector tries to access web content via the provided link in the RSS Feed but the website returns no content (e.g. http 403 error). In this case I would assume that the item would still be created but with content from the RSS Feed directly (like "content" or "description") instead of no item at all.

**Comment by b3n4kh** [comment]
I introduced a fix for this with: [c174d33](https://github.com/taranis-ai/taranis-ai/commit/c174d33a229911de6624b16ecf5df1f86da269fb)
