### ISSUE TITLE
Create a fixture that generates timestamps for E2E test data

### ISSUE THREAD

**Issue by not4Pedro** [taranis-ai/taranis-ai#226]
Create a fixture that would generate timestamps for `published` and `collected`, so the test data is not continuously outdated.

The following data should be addressed: `src/core/tests/playwright/conftest.py`

**Comment by b3n4kh** [comment]
It could be a fixture that just iterates over the news_items, assigning a published date starting `now` and decreasing with each item a random value between 1 and 4 hours.
