### ISSUE TITLE
Frontend error messages without timer

### ISSUE THREAD

**Issue by not4Pedro** [taranis-ai/taranis-ai#250]
The displayed error messages in the frontend should not disappear automatically. Or, the option to have the errors without a timer should be configurable. 

(success messages can vanish automatically)

**Comment by Alperadoss** [comment]
i'd like to solve it, would you assign me for the task?

**Comment by not4Pedro** [comment]
Hello @Alperadoss. This is an opensource project and contributions or feedback in the form of issues are always welcome. 
If you feel up to the task, we will happily review any valuable contributions with respect to our time constraints. Best, P.
