### ISSUE TITLE
Document: XPATH can fail due to JavaScript

### ISSUE THREAD

**Issue by not4Pedro** [taranis-ai/taranis-ai#269]
Document that the XPATH can fail in case of JavaScript dependency. If elements of Xpath locators are rendered by javascript, then the collector is not able to find the element. Document this fact and consider that there is an open issue #290 which should solve the issue with digest splitting of javascript content

_______________________________________________
Some XPaths that work in chrome (DevTools) can not be used with the collector, since they only are available with JavaScript enabled. Example below:
```
if __name__ == "__main__":
    collector = SimpleWebCollector()
    collector.collect({"id": "test", "parameters": {
    "WEB_URL": "https://rubryka.com/en",
    "XPATH": "//*[@id='mCSB_1_container']",
    "DIGEST_SPLITTING": "true"
    }})
```

Error handling for these cases should be improved.

**Comment by b3n4kh** [comment]
This was generally fixed with #24

There should be an error message indicating that the XPATH is either valid or invalid (raise error if not) and if it is valid and there is no content returned that the main reason for this to happen is usually an issue with not having the fields present **without javascript**

**Comment by not4Pedro** [comment]
> This was generally fixed with #24
> 
> There should be an error message indicating that the XPATH is either valid or invalid (raise error if not) and if it is valid and there is no content returned that the main reason for this to happen is usually an issue with not having the fields present **without javascript**

There is a [library](https://requests.readthedocs.io/projects/requests-html/en/latest/#javascript-support) working with javascript, it might be worthwhile checking it out. However, my brief testing was not very successful.

**Comment by b3n4kh** [comment]
We have the selenium based web collector for this.

**Comment by not4Pedro** [comment]
Would we want to add XPath and Digest Splitting support there then?

**Comment by b3n4kh** [comment]
[web_collector.py](https://github.com/taranis-ai/taranis-ai/blob/master/src/worker/worker/collectors/web_collector.py) has XPath support. Adding something like digest splitting support to, it could be tracked via a separate issue.

Even tough, that worker would probably need some tests and QA first.

**Comment by not4Pedro** [comment]
@b3n4kh okay, I checked only the frontend and the selectors work differently there, so I got confused. Let's track it via a separate issue.
