### ISSUE TITLE
Assess: NewsItems manually created are not visible in Assess on filter

### ISSUE THREAD

**Issue by not4Pedro** [taranis-ai/taranis-ai#272]
Items that are created manually are not present in Assess when time window filter applied.

**Comment by b3n4kh** [comment]
This seems to be a documentation issue / UX issue.

First Day: is applied to the story creation date, which usually corresponds to the "published date" of the oldest news item.
Last Day: is applied to the story last update date, which usually corresponds to the last time an item was added to the story or any other kind of manipulation was done to it.

By manually created stories this "updated" timestamp is basically the creation time, so filtering for "last day" for a manual created one will not yield the story even it an old "published date" is set.

This definitely needs better documentation and probably also some UX improvements in the frontend

**Comment by b3n4kh** [comment]
It should be user configureable if `Last Day ` should filter based on "story.updated" or based on "latest collected date"

**Comment by not4Pedro** [comment]
Docs will be updated, and a hyperlink in the filter area in Assess should be added to this new documentation.

**Comment by b3n4kh** [comment]
After is merged add deep link to https://taranis.ai/docs/assess/ from the AssessNav (top or bottom)  which would solve this issue.
