### ISSUE TITLE
Filter bar not showing up

### ISSUE THREAD

**Issue by leonstiegler** [taranis-ai/taranis-ai#308]
As mentioned in the title the bar including the filter options is not showing:

![grafik](https://github.com/user-attachments/assets/f739d32e-e3fe-4d5f-8cbf-2bbeaf93b12e)

When clicking the button to open the bar nothing happens except of the news items changing the sizing:

![grafik](https://github.com/user-attachments/assets/9d26d20f-bf1d-4974-948d-0837f39f12f7)

Here are the errors in the JS console:

`TypeError: a.end_of_shift is null
    setup AssessNav.vue:259
    lt runtime-core.esm-bundler.js:202
    eu runtime-core.esm-bundler.js:7705
    Zc runtime-core.esm-bundler.js:7665
    le runtime-core.esm-bundler.js:4873
    Q runtime-core.esm-bundler.js:4839
    R runtime-core.esm-bundler.js:4357
    A runtime-core.esm-bundler.js:5063
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:5107
    me runtime-core.esm-bundler.js:4916
    Q runtime-core.esm-bundler.js:4850
    R runtime-core.esm-bundler.js:4357
    A runtime-core.esm-bundler.js:5063
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:5107
    lt runtime-core.esm-bundler.js:202
    Xo runtime-core.esm-bundler.js:416
    promise callback*Yo runtime-core.esm-bundler.js:326
    ys runtime-core.esm-bundler.js:346
    Uc runtime-core.esm-bundler.js:7120
    b runtime-core.esm-bundler.js:5963
    js reactivity.esm-bundler.js:262
    Mo reactivity.esm-bundler.js:306
    zt reactivity.esm-bundler.js:1079
    set value reactivity.esm-bundler.js:1126
    F vue-router.mjs:3460
    ya/$/< vue-router.mjs:3325
    promise callback*$ vue-router.mjs:3292
    O vue-router.mjs:3217
    install vue-router.mjs:3659
    use runtime-core.esm-bundler.js:2572
    QB main.js:25
    <anonymous> main.js:56
runtime-core.esm-bundler.js:277:12
`

`TypeError: e.storyFilter is undefined
    ke AssessNav.vue:4
    rs runtime-core.esm-bundler.js:6301
    A runtime-core.esm-bundler.js:4976
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:5107
    re runtime-core.esm-bundler.js:5117
    le runtime-core.esm-bundler.js:4886
    Q runtime-core.esm-bundler.js:4839
    R runtime-core.esm-bundler.js:4357
    A runtime-core.esm-bundler.js:5063
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:5107
    me runtime-core.esm-bundler.js:4916
    Q runtime-core.esm-bundler.js:4850
    R runtime-core.esm-bundler.js:4357
    A runtime-core.esm-bundler.js:5063
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:5107
    lt runtime-core.esm-bundler.js:202
    Xo runtime-core.esm-bundler.js:416
    promise callback*Yo runtime-core.esm-bundler.js:326
    ys runtime-core.esm-bundler.js:346
    Uc runtime-core.esm-bundler.js:7120
    b runtime-core.esm-bundler.js:5963
    js reactivity.esm-bundler.js:262
    Mo reactivity.esm-bundler.js:306
    zt reactivity.esm-bundler.js:1079
    set value reactivity.esm-bundler.js:1126
    F vue-router.mjs:3460
    ya/$/< vue-router.mjs:3325
    promise callback*$ vue-router.mjs:3292
    O vue-router.mjs:3217
    install vue-router.mjs:3659
    use runtime-core.esm-bundler.js:2572
    QB main.js:25
    <anonymous> main.js:56
runtime-core.esm-bundler.js:277:12
`

Restarting and new deployment didn't help.
The error occurs in Firefox and Edge.

**Comment by not4Pedro** [comment]
@leonstiegler Thank you for reporting your issue. To workaround the first issue, set the EndOfShift in the "User settings" to an arbitrary value (time). That should allow you to use the left hand side panel.

I can't reproduce the second error, however, I get:

```
TypeError: storyFilterQuery is null
    appendStories AssessStore.js:94
    wrapAction pinia.mjs:1380
    actionName pinia.mjs:935
    displayMore AssessView.vue:122
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    emit runtime-core.esm-bundler.js:726
    createSetupContext/get emit/< runtime-core.esm-bundler.js:7820
    intersecting VInfiniteScroll.tsx:208
    handleIntersect VInfiniteScroll.tsx:172
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    emit runtime-core.esm-bundler.js:726
    createSetupContext/get emit/< runtime-core.esm-bundler.js:7820
    setup VInfiniteScroll.tsx:91
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    job runtime-core.esm-bundler.js:6096
    callWithErrorHandling runtime-core.esm-bundler.js:195
    flushJobs runtime-core.esm-bundler.js:409
    promise callback*queueFlush runtime-core.esm-bundler.js:319
    queueJob runtime-core.esm-bundler.js:313
    scheduler runtime-core.esm-bundler.js:6117
    resetScheduling reactivity.esm-bundler.js:262
    triggerEffects reactivity.esm-bundler.js:306
    triggerRefValue reactivity.esm-bundler.js:1071
    set value reactivity.esm-bundler.js:1118
    observer intersectionObserver.ts:13
    IntersectionObserver single-file-hooks-frames.js:1
    useIntersectionObserver intersectionObserver.ts:10
    setup VInfiniteScroll.tsx:85
    setup defineComponent.tsx:123
    callWithErrorHandling runtime-core.esm-bundler.js:195
    setupStatefulComponent runtime-core.esm-bundler.js:7633
    setupComponent runtime-core.esm-bundler.js:7594
    mountComponent runtime-core.esm-bundler.js:5030
    processComponent runtime-core.esm-bundler.js:4996
    patch runtime-core.esm-bundler.js:4468
    patchKeyedChildren runtime-core.esm-bundler.js:5549
    patchChildren runtime-core.esm-bundler.js:5331
    patchElement runtime-core.esm-bundler.js:4760
    processElement runtime-core.esm-bundler.js:4599
    patch runtime-core.esm-bundler.js:4456
    componentUpdateFn runtime-core.esm-bundler.js:5220
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:5264
    callWithErrorHandling runtime-core.esm-bundler.js:195
    flushJobs runtime-core.esm-bundler.js:409
    flushJobs runtime-core.esm-bundler.js:419
    promise callback*queueFlush runtime-core.esm-bundler.js:319
    queuePostFlushCb runtime-core.esm-bundler.js:339
    queueEffectWithSuspense runtime-core.esm-bundler.js:1760
    scheduler runtime-core.esm-bundler.js:6113
    resetScheduling reactivity.esm-bundler.js:262
    triggerEffects reactivity.esm-bundler.js:306
    triggerRefValue reactivity.esm-bundler.js:1071
    set value reactivity.esm-bundler.js:1118
    finalizeNavigation vue-router.mjs:3460
    pushWithRedirect vue-router.mjs:3325
    promise callback*pushWithRedirect vue-router.mjs:3292
    push vue-router.mjs:3217
    install vue-router.mjs:3659
    use runtime-core.esm-bundler.js:2984
    initializeApp main.js:25
    <anonymous> main.js:56
AssessStore.js:126:16
```
