### ISSUE TITLE
"@" Symbols in links to articles get normalized and break the link 

### ISSUE THREAD

**Issue by SaltySolomon** [taranis-ai/taranis-ai#313]
When having an @ in a URL of an article it gets broken due to normalization, example is a Mastodon RSS ingested source, example URL:

https://cyberplace.social/%40GossiTheDog/112994089425914282

Should be:
https://cyberplace.social/@GossiTheDog/112994089425914282

**Comment by b3n4kh** [comment]
This is a bug in [sanitze_url in base_collector](https://github.com/taranis-ai/taranis-ai/blob/master/src/worker/worker/collectors/base_collector.py#L66).

'@' should be in the list of safe characters, there are even more characters missing being compliant with: https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

safe characters should be at least: `/:@?&=+$,;`
