### ISSUE TITLE
Implement useful error messages on Collectors

### ISSUE THREAD

**Issue by SaltySolomon** [taranis-ai/taranis-ai#314]
Currently getting this error on a bunch of collectors. The error isn't helpful, it would be nice if the errorhandling would improve and indicate what the issue is:

Error
An error occurred while gathering the source
the JSON object must be str, bytes or bytearray, not dict

**Comment by b3n4kh** [comment]
`the JSON object must be str, bytes or bytearray, not dict` could be related to `ADDITIONAL_HEADERS` not being parsed correctly. This is most probably a bug in [update_headers in base_web_collector](https://github.com/taranis-ai/taranis-ai/blob/master/src/worker/worker/collectors/base_web_collector.py#L51) which only catches `JSONDecodeError` but not the `TypeError` - which is the error seen in this case.
