### ISSUE TITLE
Merging stories present in a report breaks things (prevents product to render)

### ISSUE THREAD

**Issue by not4Pedro** [taranis-ai/taranis-ai#323]
- merging or deleting a story while added to a report will break this report, which makes it unable to be rendered
- => probably needs some improvements in: 
[taranis-ai/taranis-ai/src/core/core/model/story.py](https://github.com/taranis-ai/taranis-ai/blob/f68fb4a94f5321a42b7499c193c0c35d9d308d39/src/core/core/model/story.py#L766)

- Add an (E2E) test

**Comment by b3n4kh** [comment]
Fixed with #332
