### ISSUE TITLE
Creating a user fails with the error "Could not create this user."

### ISSUE THREAD

**Issue by SaltySolomon** [taranis-ai/taranis-ai#335]
Hi,

in our instance creation of a new user fails with "Could not create this user.".

Not sure if the issue is our instance or not, haven't gotten around to trying a fresh install but the error message is definitly not helpfull tracking down the issue.

**Comment by trizzosk** [comment]
I do have the same issue on a cleanly deployed instance.

**Comment by not4Pedro** [comment]
Thank you for reporting this issue.

It seems to be a bug indeed, introduced by this commit c5a95e48bd4541daac1aa837122c10ec23ed94d5 where the `permissions` parameter was removed from the `__init__()` function in [user.py](https://github.com/taranis-ai/taranis-ai/commit/c5a95e48bd4541daac1aa837122c10ec23ed94d5#diff-19f336e10d99731a40c46f7bb448779c853efd3a406768751092fbadd4dabe4a)
