### ISSUE TITLE
Add/edit product

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#37]
From Taranis-NG created by [ewoiset](https://github.com/ewoiset): ait-cs-IaaS/Taranis-NG#94  

add following functionality to http://localhost:8082/product/{id} - same for "new" and "update"
- display report items as table (similar to "config/reportitems/attributes") 
- rendering product in frontend
- enable functionality

**Improve Products to allow setting related report types**

The problem is that when a user creates a "product" he can select a report that is of a type that is not compatible with the current product.

![Screenshot from 2024-01-09 10-29-06](https://github.com/taranis-ai/taranis-ai/assets/6696618/e6702e26-2d6e-4b96-828a-3d273a48daa8)

This resulted in hacks like the one shown above.  Which would simply render a broken report so that the rendering doesn't crash completely, that was the "hack" from upstream to work around the issue.

**Comment by ewoiset** [comment]
Testing: 

admin: 
- add report type
- add product type + select report types 

user: 
- CRUD products 
- check if product types and reports displayed are correct (based on selected report types in product type)
