### ISSUE TITLE
ACLs various issues

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#47]
From Taranis-NG created by [ewoiset](https://github.com/ewoiset): ait-cs-IaaS/Taranis-NG#68  

There are various issues with creating and updating ACLs, that should be tested.

- [ ] roles and users not stored in dictionary
- [ ] "everyone" is automatically set to true, even if it is not set 
- [ ] update throws sql error: 
```
sqlalchemy.exc.StatementError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(builtins.LookupError) '1' is not among the defined enum values. Enum name: itemtype. Possible values: OSINT_SOURC.., OSINT_SOURC.., WORD_LIST, ..., DELEGATION
[SQL: UPDATE acl_entry SET item_type=%(item_type)s WHERE acl_entry.id = %(acl_entry_id)s]

``` 

- [ ] update tests

**Comment by ewoiset** [comment]
meeting 2023-12-04: 


- TLP Klassifizierung 
- Klassifikation in Item automatisch aus Quelle 
- Report(template) hat Klassifizierungsattribut 
- Klassifikation bei Item änderbar wenn in Report ""warning"" --> gesamtes Item wird angepasst 
- Visuelle Darstellung der Klassifizierung "


also see issue #86

**Comment by b3n4kh** [comment]
Consider manually created items for acl_check in news items. => https://github.com/taranis-ai/taranis-ai/issues/101
