### ISSUE TITLE
Update wiki on OSINT source collection workflow

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#6]
From taranis-ai created by [b3n4kh](https://github.com/b3n4kh): taranis-ai/taranis-ai#2  

From Taranis-NG created by [ewoiset](https://github.com/ewoiset): ait-cs-IaaS/Taranis-NG#176  

Write/update doku for OSINT source collection workflow https://github.com/ait-cs-IaaS/Taranis-NG/wiki/OSINT-workflow

following steps need to be described 
1) add OSINT sources 
2) Add and adapt word lists --> which list / tagging bot etc 
3) Activate wordlists to filter in default source group (all sources are in tehre) 
4) Define which bots should run after collection 
5) Run Collect Sources

**Comment by b3n4kh** [comment]
upload images as relative path (see other docu)

**Comment by ewoiset** [comment]
@b3n4kh  bitte kurz drüber schauen https://taranis.ai/documentation/osint-workflow/

**Comment by b3n4kh** [comment]
Solved with the new documentation under: https://taranis.ai/documentation/osint-workflow/
