### ISSUE TITLE
Change evaluations to None in model update methods

### ISSUE THREAD

**Issue by ewoiset** [taranis-ai/taranis-ai#70]
change https://github.com/taranis-ai/taranis-ai/blob/master/src/core/core/model/product.py#L169 to https://github.com/taranis-ai/taranis-ai/blob/master/src/core/core/model/product.py#L175

**Comment by not4Pedro** [comment]
https://github.com/taranis-ai/taranis-ai/commit/9c14366ae8134b5e8413875350613371af393d07

**Comment by ewoiset** [comment]
@b3n4kh  is it correct to change it in entire core?
