### ISSUE TITLE
AssessNav cleanup

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#77]
* Add "time frame" (18h - 18h) to AssessNav
* Remove Debug
* Change all items in [filterSelectList](https://github.com/taranis-ai/taranis-ai/blob/master/src/gui/src/components/assess/filter/filterSelectList.vue) to match the one of [filterSortList](https://github.com/taranis-ai/taranis-ai/blob/master/src/gui/src/components/assess/filter/filterSortList.vue)
  So if a user presses "read" once it filters for all items that are marked as read, if he presses a second time it filters all items that are **not** marked as read, pressing a third time resets the button and the "read" status is ignored again.

**Comment by ewoiset** [comment]
meeting 2023-12-04: "infinite scroll" functionality should be discussed in more detail

**Comment by b3n4kh** [comment]
Add "time frame" (18h - 18h) to AssessNav

**Comment by b3n4kh** [comment]
Solved by #157
