### ISSUE TITLE
e2e tests with playwright

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#78]
Add e2e tests with playwright.

The tests should produce a screen recording for manual verification and documentation purposes.

```
from playwright.sync_api import sync_playwright

def run(playwright):
    chromium = playwright.chromium
    browser = chromium.launch()
    context = browser.new_context(record_video_dir='videos/')
    page = context.new_page()

    page.goto('http://localhost:8080')
    # Workflow

    page.close()
    context.close()
    browser.close()

with sync_playwright() as p:
    run(p)
```

Steps to test:

```
Dashboard => Click on 'SQL Injection' Tag

Click expand on the Lazarus Group Story
Click on Tag Spain

Click Reset Filter

Click Filter ⇾ Week
Click Sort   ⇾ relevance

Click WS-FTP Tag

Choose WS-FTP Story to add to Report


Click Analyze

Click Report "Vulnerability"
Enter text into first field

Toggle "completed"

Click Save

Click Publish

Click TestReport
```

**Comment by b3n4kh** [comment]
1. step is to create a compose.yml to bootstrap everything for e2e testing while importing an existing database dump.

2. Create minimal playwright config that just logs into the database.

**Comment by not4Pedro** [comment]
Scenario dependencies: 
* A report created beforehand
* "Relevance" of stories needs to be set beforehand

**Comment by not4Pedro** [comment]
Status update:
* Tests pass locally
* In headless mode a bit of inconsistency was discovered, when the `slow_mo` is low (works well with `slow_mo=500`)
* Tests in the CI are broken. They fail on several random button with timeouts. To overcome these timeouts, clicking problematic button multiple times helps (although not always possible). (implementing it in [async](https://playwright.dev/python/docs/library#usage) could be tried to overcome the issue)
* I was unable to use the tracing flag `--tracing=on` properly. 
* Although, screenshots and videos work as expected.
* The workflow of the videos is hard to follow without any highlighting of clicked objects.

**Comment by not4Pedro** [comment]
Putting this into Backlog for now, it makes sense to wait for UI updates and revisit it later.

**Comment by b3n4kh** [comment]
GitHub Action support was postponed for now, the last approach can be found here:

[playwright_github_action.zip](https://github.com/taranis-ai/taranis-ai/files/13888818/playwright_github_action.zip)
