### ISSUE TITLE
RT Collector

### ISSUE THREAD

**Issue by b3n4kh** [taranis-ai/taranis-ai#80]
Create a collector that parses all issues from [RT](https://github.com/bestpractical/rt) instance

See example for how to access:
https://rt-wiki.bestpractical.com/wiki/REST#Ticket_Search

Create Dockerfile for integration tests similar to:
https://github.com/bestpractical/docker-rt-debian-stretch/blob/master/Dockerfile

**Comment by not4Pedro** [comment]
A test containter to use https://github.com/netsandbox/docker-rt

**Comment by not4Pedro** [comment]
TODO: 
Improve values returned as a dict. The address could be the RT address and so on and so forth.
